language: node_js

branches:
  only:
    - gh-pages

node_js:
  - "6"  

env:
  - TASK=default

install:
  - scripts/setup-ubuntu
  - source ~/.bashrc
  - nvm use 6.2

script:
  - scripts/update-webppl
  - scripts/update-editor
  - scripts/update-viz

sudo: required
dist: trusty
