#!/bin/bash
set -e
set -x

sudo apt-get install -y build-essential libssl-dev pkg-config libcairo2-dev libjpeg-dev libgif-dev
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.31.1/install.sh | bash
source ~/.nvm/nvm.sh
export -f nvm
nvm install 6.2
nvm use 6.2
npm install
npm install -g grunt grunt-cli browserify uglifyjs

echo "Success."