#!/bin/bash
set -e
set -x

sudo apt-get install build-essential libssl-dev pkg-config libcairo2-dev libjpeg-dev libgif-dev
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.31.1/install.sh | bash
source ~/.bashrc
nvm install 6.2
nvm use 6.2
git clone https://github.com/stuhlmueller/connoisseur.git
cd connoisseur
npm install
npm install -g grunt grunt-cli browserify uglifyjs

echo "Success."