#!/bin/bash
set -e
set -x

npm install --save probmods/webppl-viz
cd node_modules/vega
npm install
cd ../vega-lite
npm install
cd ../webppl-viz
npm install
grunt bundle
cp bundle/webppl-viz.min.js ../../assets/js/webppl-viz.min.js
cp bundle/webppl-viz.css ../../assets/css/webppl-viz.css
cd ../..

echo "Success."